# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-08 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='volume',
            name='album',
            field=models.ImageField(default='', upload_to=b'album', verbose_name='\u5c01\u9762'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volume',
            name='category',
            field=models.SmallIntegerField(choices=[(0, 'VOL'), (1, 'Spec'), (2, 'Weekly'), (3, 'Discuss')], db_index=True, default=0, verbose_name='\u7c7b\u578b'),
        ),
    ]
