# -*- coding: utf-8 -*-
# Generated by Django 1.11rc1 on 2017-04-04 04:02
from __future__ import unicode_literals

from django.db import migrations, models
from django.db.models import F


def upgrade_brow(apps, schema_editor):
    MacSkill = apps.get_model('news', 'MacSkill')
    MacSkill.objects.update(brow=F('id'))


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20170325_1613'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='volume',
            options={'ordering': ['-vol'], 'verbose_name': '\u8282\u76ee', 'verbose_name_plural': '\u8282\u76ee'},
        ),
        migrations.AddField(
            model_name='macskill',
            name='brow',
            field=models.SlugField(default='', verbose_name='URL'),
            preserve_default=False,
        ),
        migrations.RunPython(upgrade_brow),
        migrations.AlterField(
            model_name='macskill',
            name='brow',
            field=models.SlugField(unique=True, verbose_name='URL'),
        ),
    ]
