# -*- coding: utf-8 -*-
# Generated by Django 1.11rc1 on 2017-04-07 03:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20170404_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='macskill',
            name='is_publish',
            field=models.BooleanField(db_index=True, default=False, verbose_name='\u53d1\u5e03'),
        ),
    ]
