# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-03 16:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lease', '0002_auto_20170531_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='\u5f52\u8fd8\u65e5'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='\u5f00\u59cb\u4f7f\u7528\u65e5'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='attr',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='\u578b\u53f7'),
        ),
    ]
