# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-04 00:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_type', models.SmallIntegerField(choices=[(1, '\u5fae\u535a'), (2, '\u5fae\u4fe1')], default=1, verbose_name='\u8ba4\u8bc1\u7c7b\u578b')),
                ('auth_uid', models.BigIntegerField(verbose_name='\u7b2c\u4e09\u65b9UID')),
                ('screen_name', models.CharField(max_length=255, verbose_name='\u6635\u79f0')),
                ('access_token', models.CharField(max_length=255, verbose_name=b'access_token')),
                ('expires_in', models.DateTimeField(verbose_name='token\u8fc7\u671f')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u6863\u6848',
                'verbose_name_plural': '\u7528\u6237\u6863\u6848',
            },
        ),
        migrations.AlterUniqueTogether(
            name='profile',
            unique_together=set([('auth_type', 'auth_uid')]),
        ),
    ]
